/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FilterBar: typeof import('./../components/aitest/common/FilterBar.vue')['default']
    HomeLayout: typeof import('./../components/layout/HomeLayout.vue')['default']
    MainContent: typeof import('./../components/layout/MainContent.vue')['default']
    ModuleLayout: typeof import('./../components/layout/ModuleLayout.vue')['default']
    PriorityBadge: typeof import('./../components/aitest/common/PriorityBadge.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatusTag: typeof import('./../components/aitest/common/StatusTag.vue')['default']
    StepIndicator: typeof import('./../components/aitest/generation/StepIndicator.vue')['default']
    Topbar: typeof import('./../components/layout/Topbar.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanCellGroup: typeof import('vant/es')['CellGroup']
    VanEmpty: typeof import('vant/es')['Empty']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanSearch: typeof import('vant/es')['Search']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
  }
}
