"""Alembic 迁移脚本模板

使用 alembic revision --autogenerate -m "描述" 时自动生成此模板
"""

"""create_test_management_tables

Revision ID: 0221dd3017e1
Revises: d4c4880b8b6f
Create Date: 2026-06-14 18:36:57.131943
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0221dd3017e1'
down_revision: Union[str, None] = 'd4c4880b8b6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移：应用变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_project',
    sa.Column('name', sa.String(length=200), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('leader', sa.String(length=50), nullable=True, comment='负责人'),
    sa.Column('start_date', sa.Date(), nullable=True, comment='开始日期'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='结束日期'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（active=进行中/completed=已完成/archived=已归档）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色（admin=管理员/tester=测试工程师/viewer=访客）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_review',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='关联项目ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='评审名称'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（pending=待评审/passed=通过/rejected=驳回）'),
    sa.Column('cases', mysql.JSON(), nullable=True, comment='用例列表（JSON格式）'),
    sa.Column('conclusion', sa.Text(), nullable=True, comment='评审结论'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_version',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='关联项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='版本号/版本名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本描述'),
    sa.Column('changelog', sa.Text(), nullable=True, comment='变更内容'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（released=已发布/in_progress=进行中/obsolete=已废弃）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_assignment',
    sa.Column('review_id', sa.Integer(), nullable=False, comment='评审ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='评审人ID'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（pending=待评审/approved=通过/rejected=驳回）'),
    sa.Column('comment', sa.Text(), nullable=True, comment='评审意见'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['review_id'], ['test_review.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_case',
    sa.Column('project_id', sa.Integer(), nullable=True, comment='关联项目ID'),
    sa.Column('version_id', sa.Integer(), nullable=True, comment='关联版本ID'),
    sa.Column('module', sa.String(length=100), nullable=True, comment='模块名称'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='用例标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='用例描述'),
    sa.Column('priority', sa.String(length=20), nullable=True, comment='优先级（p0/p1/p2/p3）'),
    sa.Column('precondition', sa.Text(), nullable=True, comment='前置条件'),
    sa.Column('test_steps', sa.Text(), nullable=True, comment='测试步骤'),
    sa.Column('expected_result', sa.Text(), nullable=True, comment='预期结果'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（draft/active/deprecated）'),
    sa.Column('test_type', sa.String(length=20), nullable=True, comment='测试类型（functional/api/ui/app）'),
    sa.Column('source', sa.String(length=20), nullable=True, comment='来源（ai_generated/manual/imported）'),
    sa.Column('tags', mysql.JSON(), nullable=True, comment='标签列表'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['test_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移：撤销变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_case')
    op.drop_table('review_assignment')
    op.drop_table('test_version')
    op.drop_table('test_review')
    op.drop_table('project_member')
    op.drop_table('test_project')
    # ### end Alembic commands ###
