"""Alembic 迁移脚本模板

使用 alembic revision --autogenerate -m "描述" 时自动生成此模板
"""

"""init

Revision ID: 4739171df31e
Revises: 
Create Date: 2026-06-14 16:57:05.995248
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4739171df31e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移：应用变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移：撤销变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
