"""Alembic 迁移脚本模板

使用 alembic revision --autogenerate -m "描述" 时自动生成此模板
"""

"""add pipeline_type to ai_generation_task

Revision ID: 710c36bc7de3
Revises: 7ae06c474002
Create Date: 2026-06-17 23:44:02.280849
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '710c36bc7de3'
down_revision: Union[str, None] = '7ae06c474002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移：应用变更"""
    op.add_column('ai_generation_task', sa.Column('pipeline_type', sa.String(length=20), nullable=True, comment='管线类型（traditional/langgraph/autogen）'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移：撤销变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ai_generation_task', 'pipeline_type')
    # ### end Alembic commands ###
