"""Alembic 迁移脚本模板

使用 alembic revision --autogenerate -m "描述" 时自动生成此模板
"""

"""add_p1_models

Revision ID: d4c4880b8b6f
Revises: 4739171df31e
Create Date: 2026-06-14 17:55:10.638587
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd4c4880b8b6f'
down_revision: Union[str, None] = '4739171df31e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """升级迁移：应用变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_environment',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='环境名称'),
    sa.Column('base_url', sa.String(length=500), nullable=False, comment='基础URL'),
    sa.Column('variables', sa.JSON(), nullable=True, comment='环境变量（键值对）'),
    sa.Column('headers', sa.JSON(), nullable=True, comment='请求头（键值对）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（active/inactive）'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_project',
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('base_url', sa.String(length=500), nullable=True, comment='基础 URL'),
    sa.Column('swagger_url', sa.String(length=500), nullable=True, comment='Swagger URL'),
    sa.Column('version', sa.String(length=50), nullable=True, comment='API 版本'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（active/archived）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_project',
    sa.Column('name', sa.String(length=100), nullable=False, comment='项目名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='项目描述'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（active/archived）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_endpoint',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='接口名称'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='接口路径'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP 方法（GET/POST/PUT/DELETE/PATCH）'),
    sa.Column('tag', sa.String(length=100), nullable=True, comment='接口标签/分类'),
    sa.Column('description', sa.Text(), nullable=True, comment='接口描述'),
    sa.Column('request_params', mysql.JSON(), nullable=True, comment='请求参数（JSON）'),
    sa.Column('request_headers', mysql.JSON(), nullable=True, comment='请求头（JSON）'),
    sa.Column('request_body', mysql.JSON(), nullable=True, comment='请求体 Schema（JSON）'),
    sa.Column('response_example', mysql.JSON(), nullable=True, comment='响应示例（JSON）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（active/disabled）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['api_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_test_suite',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='所属项目 ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='套件名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='套件描述'),
    sa.Column('endpoints_config', mysql.JSON(), nullable=True, comment='接口顺序和配置（JSON）'),
    sa.Column('assertions', mysql.JSON(), nullable=True, comment='断言规则（JSON）'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（draft/ready/running/completed/failed）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者 ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['api_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_member',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='项目ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role', sa.String(length=20), nullable=True, comment='角色（admin/maintainer/developer/viewer）'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_version',
    sa.Column('project_id', sa.Integer(), nullable=False, comment='关联项目ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='版本名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='版本描述'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（planning/in_progress/completed/released/archived）'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['test_project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_schedule',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='任务名称'),
    sa.Column('suite_id', sa.Integer(), nullable=False, comment='关联测试套件ID'),
    sa.Column('environment_id', sa.Integer(), nullable=True, comment='关联环境ID'),
    sa.Column('cron_expression', sa.String(length=100), nullable=False, comment='Cron表达式'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（running/paused/stopped）'),
    sa.Column('notify', sa.JSON(), nullable=True, comment='通知配置（{email, webhook, on_failure_only}）'),
    sa.Column('last_run_at', sa.DateTime(), nullable=True, comment='上次执行时间'),
    sa.Column('next_run_at', sa.DateTime(), nullable=True, comment='下次执行时间'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['environment_id'], ['api_environment.id'], ),
    sa.ForeignKeyConstraint(['suite_id'], ['api_test_suite.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_review',
    sa.Column('version_id', sa.Integer(), nullable=False, comment='关联版本ID'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='评审名称'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态（pending/in_progress/passed/rejected）'),
    sa.Column('cases', mysql.JSON(), nullable=True, comment='用例列表（JSON格式）'),
    sa.Column('conclusion', sa.Text(), nullable=True, comment='评审结论'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='创建者ID'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['version_id'], ['test_version.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """降级迁移：撤销变更"""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_review')
    op.drop_table('api_schedule')
    op.drop_table('test_version')
    op.drop_table('project_member')
    op.drop_table('api_test_suite')
    op.drop_table('api_endpoint')
    op.drop_table('test_project')
    op.drop_table('api_project')
    op.drop_table('api_environment')
    # ### end Alembic commands ###
